import { Student } from "../../../shared/models/student.model";

export const DUMMY_STUDENT: Student[] = [
  { 
    id:'001',
    name: 'madhusudan',
    rollNo: '12',
    class: '10',
    section: 'B',
    attendance: 93,
    lastMarks: 90,
    healthScore: 96,
    status: 'active',
  },
   {
    id:'002',
    name: 'saurabh',
    rollNo: '12',
    class: '8',
    section: 'B',
    attendance: 80,
    lastMarks: 90,
    healthScore: 85,
    status: 'active',
  },
   {
    id:'003',
    name: 'Gaurav',
    rollNo: '13',
    class: '10',
    section: 'B',
    attendance: 20,
    lastMarks: 90,
    healthScore: 20,
    status: 'at-risk',
  },
   {
    id:'004',
    name: 'Rishi',
    rollNo: '18',
    class: '10',
    section: 'B',
    attendance: 60,
    lastMarks: 90,
    healthScore: 20,
    status: 'watch',
  },
   {
    id:'005',
    name: 'Hitesh',
    rollNo: '20',
    class: '10',
    section: 'B',
    attendance: 20,
    lastMarks: 90,
    healthScore: 20,
    status: 'at-risk',
  },
];